collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8020256
  brandStrength: 0.3786804336123168
  rhythmicContrast: 0.2508961
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  lightness: 0.7530072
typography_spectrum: 0.1612903
layout_spectrum: 0.4820789
name: ODsynth
