collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8020255612209439
  brandStrength: 0.6290323
  lightness: 0.7530071979854256
  brandColors:
    - '#C9BFB3'
    - '#28272C'
    - '#9A9A92'
    - '#716E69'
    - '#A94131'
  rhythmicContrast: 0.5774955579545349
typography_spectrum: 0.2795699
layout_spectrum: 0.2616487
name: ODsynth
